# Generated by Django 4.2.11 on 2024-04-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_foodnutrient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labmethodcode',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
