# Generated by Django 4.2.11 on 2024-04-21 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_labmethodcode_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodnutrient',
            table='food1_nutrient',
        ),
    ]
